// Code generated by hertz generator.

package main

import (
	"dousheng/router/biz/logger"

	"github.com/cloudwego/hertz/pkg/app/server"
	pprof "github.com/hertz-contrib/pprof"
)

func main() {
	h := server.Default(server.WithMaxRequestBodySize(20 << 20) /*20MB*/)

	h.Use(logger.AccessLog())
	pprof.Register(h)
	register(h)
	h.Spin()
}
